import type { Metadata } from "next";
import { ToastContainer, toast } from "react-toastify";
import { Providers } from "./provider";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ToastContainer hideProgressBar stacked/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
